### ISSUE TITLE
get rid of std::atoi

### ISSUE THREAD

**Issue by ghost** [psemiletov/mtag#1]
http://www.cplusplus.com/reference/cstdlib/atoi/

1) atoi returns 0 if input string is not an int
2) atoi causes UB for some inputs

**Comment by psemiletov** [comment]
atoi is the most simply way to do the task, I don't want to make the code complex.

**Comment by ghost** [comment]
It is just wrong to parse user input with std::atoi in all cases. However, that is up to you what to do with your code.

**Comment by psemiletov** [comment]
changed to stoi instead
